/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProductRouteImport } from './routes/product'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MiceEventsRouteImport } from './routes/mice-events'
import { Route as CorporateTravelManagementDelhiRouteImport } from './routes/corporate-travel-management-delhi'
import { Route as CorporateTravelManagementChennaiRouteImport } from './routes/corporate-travel-management-chennai'
import { Route as CorporateTravelManagementBangaloreRouteImport } from './routes/corporate-travel-management-bangalore'
import { Route as CbtRouteImport } from './routes/cbt'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as B2eRouteImport } from './routes/b2e'
import { Route as B2bRouteImport } from './routes/b2b'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogsIndexRouteImport } from './routes/blogs.index'
import { Route as BlogsSlugRouteImport } from './routes/blogs.$slug'
import { Route as AdminRegistrationsRouteImport } from './routes/admin/registrations'
import { Route as AdminLoginRouteImport } from './routes/admin/login'

const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MiceEventsRoute = MiceEventsRouteImport.update({
  id: '/mice-events',
  path: '/mice-events',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateTravelManagementDelhiRoute =
  CorporateTravelManagementDelhiRouteImport.update({
    id: '/corporate-travel-management-delhi',
    path: '/corporate-travel-management-delhi',
    getParentRoute: () => rootRouteImport,
  } as any)
const CorporateTravelManagementChennaiRoute =
  CorporateTravelManagementChennaiRouteImport.update({
    id: '/corporate-travel-management-chennai',
    path: '/corporate-travel-management-chennai',
    getParentRoute: () => rootRouteImport,
  } as any)
const CorporateTravelManagementBangaloreRoute =
  CorporateTravelManagementBangaloreRouteImport.update({
    id: '/corporate-travel-management-bangalore',
    path: '/corporate-travel-management-bangalore',
    getParentRoute: () => rootRouteImport,
  } as any)
const CbtRoute = CbtRouteImport.update({
  id: '/cbt',
  path: '/cbt',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const B2eRoute = B2eRouteImport.update({
  id: '/b2e',
  path: '/b2e',
  getParentRoute: () => rootRouteImport,
} as any)
const B2bRoute = B2bRouteImport.update({
  id: '/b2b',
  path: '/b2b',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogsRoute,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogsRoute,
} as any)
const AdminRegistrationsRoute = AdminRegistrationsRouteImport.update({
  id: '/admin/registrations',
  path: '/admin/registrations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/b2b': typeof B2bRoute
  '/b2e': typeof B2eRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/cbt': typeof CbtRoute
  '/corporate-travel-management-bangalore': typeof CorporateTravelManagementBangaloreRoute
  '/corporate-travel-management-chennai': typeof CorporateTravelManagementChennaiRoute
  '/corporate-travel-management-delhi': typeof CorporateTravelManagementDelhiRoute
  '/mice-events': typeof MiceEventsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/product': typeof ProductRoute
  '/register': typeof RegisterRoute
  '/solutions': typeof SolutionsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/blogs/': typeof BlogsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/b2b': typeof B2bRoute
  '/b2e': typeof B2eRoute
  '/cbt': typeof CbtRoute
  '/corporate-travel-management-bangalore': typeof CorporateTravelManagementBangaloreRoute
  '/corporate-travel-management-chennai': typeof CorporateTravelManagementChennaiRoute
  '/corporate-travel-management-delhi': typeof CorporateTravelManagementDelhiRoute
  '/mice-events': typeof MiceEventsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/product': typeof ProductRoute
  '/register': typeof RegisterRoute
  '/solutions': typeof SolutionsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/blogs': typeof BlogsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/b2b': typeof B2bRoute
  '/b2e': typeof B2eRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/cbt': typeof CbtRoute
  '/corporate-travel-management-bangalore': typeof CorporateTravelManagementBangaloreRoute
  '/corporate-travel-management-chennai': typeof CorporateTravelManagementChennaiRoute
  '/corporate-travel-management-delhi': typeof CorporateTravelManagementDelhiRoute
  '/mice-events': typeof MiceEventsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/product': typeof ProductRoute
  '/register': typeof RegisterRoute
  '/solutions': typeof SolutionsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/blogs/': typeof BlogsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/b2b'
    | '/b2e'
    | '/blogs'
    | '/cbt'
    | '/corporate-travel-management-bangalore'
    | '/corporate-travel-management-chennai'
    | '/corporate-travel-management-delhi'
    | '/mice-events'
    | '/pricing'
    | '/privacy'
    | '/product'
    | '/register'
    | '/solutions'
    | '/admin/login'
    | '/admin/registrations'
    | '/blogs/$slug'
    | '/blogs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/b2b'
    | '/b2e'
    | '/cbt'
    | '/corporate-travel-management-bangalore'
    | '/corporate-travel-management-chennai'
    | '/corporate-travel-management-delhi'
    | '/mice-events'
    | '/pricing'
    | '/privacy'
    | '/product'
    | '/register'
    | '/solutions'
    | '/admin/login'
    | '/admin/registrations'
    | '/blogs/$slug'
    | '/blogs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/b2b'
    | '/b2e'
    | '/blogs'
    | '/cbt'
    | '/corporate-travel-management-bangalore'
    | '/corporate-travel-management-chennai'
    | '/corporate-travel-management-delhi'
    | '/mice-events'
    | '/pricing'
    | '/privacy'
    | '/product'
    | '/register'
    | '/solutions'
    | '/admin/login'
    | '/admin/registrations'
    | '/blogs/$slug'
    | '/blogs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  B2bRoute: typeof B2bRoute
  B2eRoute: typeof B2eRoute
  BlogsRoute: typeof BlogsRouteWithChildren
  CbtRoute: typeof CbtRoute
  CorporateTravelManagementBangaloreRoute: typeof CorporateTravelManagementBangaloreRoute
  CorporateTravelManagementChennaiRoute: typeof CorporateTravelManagementChennaiRoute
  CorporateTravelManagementDelhiRoute: typeof CorporateTravelManagementDelhiRoute
  MiceEventsRoute: typeof MiceEventsRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductRoute: typeof ProductRoute
  RegisterRoute: typeof RegisterRoute
  SolutionsRoute: typeof SolutionsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminRegistrationsRoute: typeof AdminRegistrationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mice-events': {
      id: '/mice-events'
      path: '/mice-events'
      fullPath: '/mice-events'
      preLoaderRoute: typeof MiceEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-travel-management-delhi': {
      id: '/corporate-travel-management-delhi'
      path: '/corporate-travel-management-delhi'
      fullPath: '/corporate-travel-management-delhi'
      preLoaderRoute: typeof CorporateTravelManagementDelhiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-travel-management-chennai': {
      id: '/corporate-travel-management-chennai'
      path: '/corporate-travel-management-chennai'
      fullPath: '/corporate-travel-management-chennai'
      preLoaderRoute: typeof CorporateTravelManagementChennaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-travel-management-bangalore': {
      id: '/corporate-travel-management-bangalore'
      path: '/corporate-travel-management-bangalore'
      fullPath: '/corporate-travel-management-bangalore'
      preLoaderRoute: typeof CorporateTravelManagementBangaloreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cbt': {
      id: '/cbt'
      path: '/cbt'
      fullPath: '/cbt'
      preLoaderRoute: typeof CbtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b2e': {
      id: '/b2e'
      path: '/b2e'
      fullPath: '/b2e'
      preLoaderRoute: typeof B2eRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b2b': {
      id: '/b2b'
      path: '/b2b'
      fullPath: '/b2b'
      preLoaderRoute: typeof B2bRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/admin/registrations': {
      id: '/admin/registrations'
      path: '/admin/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AdminRegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogsRouteChildren {
  BlogsSlugRoute: typeof BlogsSlugRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
}

const BlogsRouteChildren: BlogsRouteChildren = {
  BlogsSlugRoute: BlogsSlugRoute,
  BlogsIndexRoute: BlogsIndexRoute,
}

const BlogsRouteWithChildren = BlogsRoute._addFileChildren(BlogsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  B2bRoute: B2bRoute,
  B2eRoute: B2eRoute,
  BlogsRoute: BlogsRouteWithChildren,
  CbtRoute: CbtRoute,
  CorporateTravelManagementBangaloreRoute:
    CorporateTravelManagementBangaloreRoute,
  CorporateTravelManagementChennaiRoute: CorporateTravelManagementChennaiRoute,
  CorporateTravelManagementDelhiRoute: CorporateTravelManagementDelhiRoute,
  MiceEventsRoute: MiceEventsRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProductRoute: ProductRoute,
  RegisterRoute: RegisterRoute,
  SolutionsRoute: SolutionsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminRegistrationsRoute: AdminRegistrationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
